stages:
  - test
  - deploy

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - docker info

test:
  script:
    - docker build -t ubuntu ./dist-docs/docker
    - docker image list
    - docker run -d --name ubuntu -it ubuntu /sbin/init
    - docker exec -e BUNDLE_GEMFILE=/var/www/html/INTER-Mediator/dist-docs/docker/Gemfile -e DISPLAY=:99.0 -i ubuntu sh -c "phpunit --configuration /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/phpunit.xml /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/INTERMediator_AllTests.php; /usr/local/bin/buster-test -r specification -c /var/www/html/INTER-Mediator/spec/buster.js; bundle; rspec --default-path=/var/www/html/INTER-Mediator/dist-docs/docker/spec -f doc -c /var/www/html/INTER-Mediator/dist-docs/docker/spec/samples/samples_spec.rb"
    - docker stop ubuntu
    - docker rm ubuntu

pages:
  stage: deploy
  script:
  - export LANG=ja_JP.UTF-8
  - uname -a
  - apk update
  - apk add --no-cache php7
  - apk add --no-cache git
  - apk add --no-cache zip
  - mkdir public
  - cd ..
  - git clone https://github.com/matthiasmullie/minify
  - cd -
  - echo 2 | ./dist-docs/buildup.sh && cd ../im_build/ && zip -r INTER-Mediator-master.zip ./INTER-Mediator/ && mv INTER-Mediator-master.zip ../INTER-Mediator/public/
  artifacts:
    paths:
    - public
  only:
  - master
