stages:
  - test
  - deploy

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - docker info

test:
  script:
    - docker run --privileged -e "container=docker" --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d --name ubuntu ubuntu:14.04 /sbin/init
    - docker exec -e BUNDLE_GEMFILE=/var/www/html/INTER-Mediator/dist-docs/docker/Gemfile -e DISPLAY=:99.0 -i ubuntu sh -c "apt-get update && apt-get -y install ruby2.0 git && git clone https://github.com/INTER-Mediator/INTER-Mediator && cd INTER-Mediator && git checkout master && gem2.0 install itamae --no-doc && itamae local dist-docs/vm-for-trial/recipe.rb; /etc/init.d/apache2 start; /etc/init.d/mysql start; /etc/init.d/postgresql start; /etc/rc.local; echo y | sh /var/www/html/INTER-Mediator/dist-docs/vm-for-trial/dbupdate.sh; bundle; phpunit --configuration /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/phpunit.xml /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/INTERMediator_AllTests.php; /usr/local/bin/buster-test -r specification -c /var/www/html/INTER-Mediator/spec/buster.js; rspec --default-path=/var/www/html/INTER-Mediator/dist-docs/docker/spec -f doc -c /var/www/html/INTER-Mediator/dist-docs/docker/spec/samples/samples_spec.rb"
    - docker stop ubuntu
    - docker rm ubuntu

pages:
  stage: deploy
  script:
  - export LANG=ja_JP.UTF-8
  - uname -a
  - apk update
  - apk add --no-cache php7
  - apk add --no-cache git
  - apk add --no-cache zip
  - mkdir public
  - cd ..
  - git clone https://github.com/matthiasmullie/minify
  - cd -
  - echo 2 | ./dist-docs/buildup.sh && cd ../im_build/ && zip -r INTER-Mediator-master.zip ./INTER-Mediator/ && mv INTER-Mediator-master.zip ../INTER-Mediator/public/
  artifacts:
    paths:
    - public
  only:
  - master
