stages:
  - test
  - deploy

image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
  - docker info

test:
  script:
    - docker build -t ubuntu ./dist-docs/docker
    - docker image list
    - docker run -d --name ubuntu -it ubuntu /bin/bash
    - docker ps -a
    - docker run -i ubuntu phpunit --debug --configuration /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/phpunit.xml /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/INTERMediator_AllTests.php

pages:
  stage: deploy
  script:
  - export LANG=ja_JP.UTF-8
  - uname -a
  - apk update
  - apk add --no-cache php7
  - apk add --no-cache git
  - apk add --no-cache zip
  - mkdir public
  - cd ..
  - git clone https://github.com/matthiasmullie/minify
  - cd -
  - echo 2 | ./dist-docs/buildup.sh && cd ../im_build/ && zip -r INTER-Mediator-master.zip ./INTER-Mediator/ && mv INTER-Mediator-master.zip ../INTER-Mediator/public/
  artifacts:
    paths:
    - public
  only:
  - master
