stages:
  - test
  - deploy

image: docker:17.12.1-ce

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - docker info

test:
  script:
    - docker run -e "container=docker" -d --name alpine alpine:latest /sbin/init
    - docker exec -e BUNDLE_GEMFILE=/INTER-Mediator/dist-docs/docker/Gemfile -e DISPLAY=:99.0 -i alpine sh -c "apk add --no-cache sudo curl ruby ruby-json ruby-io-console git && git clone https://github.com/INTER-Mediator/INTER-Mediator && cd INTER-Mediator && git checkout master && gem install itamae --no-doc && itamae local dist-docs/vm-for-trial/recipe.rb; phpunit --bootstrap /INTER-Mediator/src/vendor/autoload.php --configuration /INTER-Mediator/spec/INTER-Mediator-UnitTest/phpunit.xml /INTER-Mediator/spec/INTER-Mediator-UnitTest/INTERMediator_AllTests.php; /usr/bin/buster-test -r specification -c /INTER-Mediator/spec/buster.js"
    - docker stop alpine
    - docker rm alpine

pages:
  stage: deploy
  script:
  - export LANG=ja_JP.UTF-8
  - uname -a
  - apk update
  - apk add --no-cache php7
  - apk add --no-cache git
  - apk add --no-cache zip
  - mkdir public
  - cd ..
  - git clone https://github.com/matthiasmullie/minify
  - cd -
  - ./dist-docs/buildup.sh --core && cd ../im_build/ && zip -r INTER-Mediator-master.zip ./INTER-Mediator/ && mv INTER-Mediator-master.zip ../INTER-Mediator/public/
  artifacts:
    paths:
    - public
  only:
  - master
