language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

before_script:
  - mysql -u root < ./dist-docs/sample_schema_mysql.txt
  - cd develop-im/INTER-Mediator-UnitTest

script:
  - phpunit DB_PDO_Test.php