language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root < ./dist-docs/sample_schema_mysql.txt; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -U postgres -f ./dist-docs/sample_schema_pgsql.txt test_db; fi"
  - cd develop-im/INTER-Mediator-UnitTest

script:
  - phpunit DB_PDO_Test.php
  - phpunit INTERMediator_Test.php