version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.2-ce-git
    working_directory: ~/INTER-Mediator
    steps:
      - checkout
      - setup_remote_docker
      - run: docker run --privileged -e "container=docker" --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d --name ubuntu ubuntu:16.04 /sbin/init
      - run: docker exec -e BUNDLE_GEMFILE=/var/www/html/INTER-Mediator/dist-docs/docker/Gemfile -e DISPLAY=:99.0 -it ubuntu sh -c "apt-get update && apt-get -y install ruby git; git clone https://github.com/INTER-Mediator/INTER-Mediator; cd INTER-Mediator; git checkout master; gem install itamae --no-doc; itamae local dist-docs/vm-for-trial/recipe.rb; echo y | sh /var/www/html/INTER-Mediator/dist-docs/vm-for-trial/dbupdate.sh; /etc/rc.local; bundle"
      - run: docker exec -e DISPLAY=:99.0 -it ubuntu sh -c "phpunit --bootstrap /var/www/html/INTER-Mediator/src/vendor/autoload.php --configuration /var/www/html/INTER-Mediator/spec/INTER-Mediator-UnitTest/phpunit.xml /var/www/html/INTER-Mediator/spec/INTER-Mediator-UnitTest/INTERMediator_AllTests.php"
      - run: docker exec -e DISPLAY=:99.0 -it ubuntu sh -c "/usr/local/bin/buster-test -r specification -c /var/www/html/INTER-Mediator/spec/buster.js"
      - run: docker exec -e DISPLAY=:99.0 -it ubuntu sh -c "rspec --default-path=/var/www/html/INTER-Mediator/dist-docs/docker/spec -f doc -c /var/www/html/INTER-Mediator/dist-docs/docker/spec/samples/samples_spec.rb"
      - run: docker stop ubuntu
      - run: docker rm ubuntu
