version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.1-ce-git
    working_directory: ~/INTER-Mediator
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -al
      - run:
          command: docker build -t ubuntu ./dist-docs/docker
          no_output_timeout: 1800
      - run: docker image list
      - run: docker run -d --name ubuntu -it ubuntu /bin/bash
      - run: docker ps -a
      - run: set +e
      - run: docker run -it ubuntu phpunit --debug --configuration /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/phpunit.xml /var/www/html/INTER-Mediator/INTER-Mediator-UnitTest/INTERMediator_AllTests.php
      - run: set -e
      - run: docker run -it ubuntu npm test
      - run: docker run -it ubuntu -e BUNDLE_GEMFILE=/var/www/html/INTER-Mediator/dist-docs/docker/Gemfile bundle
      - run: docker run -it ubuntu rspec --default-path=/var/www/html/INTER-Mediator/dist-docs/docker/spec /var/www/html/INTER-Mediator/dist-docs/docker/spec/container/container_spec.rb -f doc -c
      - run: docker run -it ubuntu rspec --default-path=/var/www/html/INTER-Mediator/dist-docs/docker/spec /var/www/html/INTER-Mediator/dist-docs/docker/spec/trainingcourse/trainingcourse_spec.rb -f doc -c
